const admin_home = require('./others/admin_home'),
      set_designation = require('./others/set_designation'),
      add_faculty = require('./faculty_db_ops/add_faculty'),
      get_all_faculties = require('./faculty_db_ops/get_all_faculties'),
      delete_faculties = require('./faculty_db_ops/delete_faculties'),
      slot_creation = require('./slot_db_ops/slot_creation'),
      delete_slots = require('./slot_db_ops/delete_slots'),
      add_slots = require('./slot_db_ops/add_slots'),
      get_exam_dates = require('./date_and_time_ops/get_exam_dates'),
      pending_faculties = require('./faculty_db_ops/pending_faculty'),
      slot_info = require('./slot_db_ops/slot_info'),
      send_mails = require('./others/send_mails'),
      add_faculties = require('./faculty_db_ops/add_faculties_ex'),
      add_slots_via_excel = require('./slot_db_ops/add_slots_ex'),
      auto_allocation = require("./slot_db_ops/auto_allocation/auto_allocation")

module.exports = {
  admin_home,
  set_designation,
  add_faculty,
  get_all_faculties,
  delete_faculties,
  slot_creation,
  delete_slots,
  add_slots,
  get_exam_dates,
  pending_faculties,
  slot_info,
  send_mails,
  add_faculties,
  add_slots_via_excel,
  auto_allocation
}